### ISSUE TITLE
I love your website

### ISSUE THREAD

**Issue by FurkanToprak** [cirosantilli/cirosantilli.github.io#70]
I'd just like to say keep up the good work. I also love your wiki project.

**Comment by cirosantilli** [comment]
Thank you Furkan!!! :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: 

If you have any suggestion at all, do let me know.

Notably, I'm looking for STEM university teachers who are already using CC BY-SA for their lecture notes, so then I would volunteer to help their students learn using the website once it is ready. Finding such teachers is going to be hard :)

I'll be dumping major project updates on Twitter, notably when the minimal prototype starts working. Minimal prototype will be simple, "just" a matter of me getting back to speed on webdev/deciding upon framework. From your website I saw you are a Flask person. I wish there was a good Node.js framework instead (since cirodown is nodejs and to reduce front/backend cognition effor), but if I don't find one I might go for Python.

**Comment by FurkanToprak** [comment]
Indeed, it is difficult to come by CC lecture notes. I was directed to your work in my Operating Systems class by my professor. 
![image](https://user-images.githubusercontent.com/46634307/110346436-29cdcb80-7ff5-11eb-8f80-4323e350b9f7.png)
Although her powerpoints are based on our textbook, Silberschatz's _Operating System Concepts,_ she may have her own notes to offer. I will ask her about her notes when I get a chance.

I'd be happy to talk about possible frameworks with you. While I have my hands full with a passion project right now, I'd be happy to help design your website architecture. If you need me, you can find me at [furkantoprak.com](https://www.furkantoprak.com)

**Comment by cirosantilli** [comment]
Cool, fun to know my tutorial was referenced, and thanks for looking into the CC thing :)

Even better would be something in Mathematics/Physics as those subjects change less with time than programming, but beggars can't be choosers. 

If you have any architecture suggestions, do drop them here.

Cheers!

**Comment by FurkanToprak** [comment]
Flask is probably your best bet. It's less of a pain in the ass with middleware, faster to write, and much more readable (which encourages more contributions). A React + Typescript front end would allow for scalability and data schema to be preserved, which would be essential in a project of this complexity. 

I'm afraid the Physics department at my school has no incentive to share any notes, as one of two textbooks is allowed and I believe both are written by a professor here. I'm afraid I'm not as well acquainted with the Maths department, but I'll see if there are any open-source notes available by anyone I know. What's stopping you from scraping websites [like this](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/)? 

PS: Cirodown is awesome and someone should make a VSCode editor for it, with preview.

Also, how would one find your contact information or -better yet- become your friend?

**Comment by cirosantilli** [comment]
> Flask is probably your best bet. It's less of a pain in the ass with middleware, faster to write, and much more readable (which encourages more contributions). A React + Typescript front end would allow for scalability and data schema to be preserved, which would be essential in a project of this complexity.
> 

Cool, I'll consider this stack.

> I'm afraid the Physics department at my school has no incentive to share any notes, as one of two textbooks is allowed and I believe both are written by a professor here. I'm afraid I'm not as well acquainted with the Maths department, but I'll see if there are any open-source notes available by anyone I know. What's stopping you from scraping websites [like this](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/)?
> 

Yes, no teacher basically has any incentive to share notes unless they are truly enlightened. That's why I want to get students to write the books :)

Yes, MIT OpenCourseWare is great, and finding universities that are forcing teachers to use CC is perhaps the best bet. The problem with OpenCourseWare is CC BY-NC-SA, and I'd really like to stay away from NC, as I find it is too restrictive/broad.

> PS: Cirodown is awesome and someone should make a VSCode editor for it, with preview.
> 

Absolutely, the dream would be to have an amazing local editor, and even more so in a way that is completely factored out with what will be present on the website. I wonder if the Monaco editor currently used on the preview http://cirosantilli.com/cirodown/editor would work easily on VSCode.

My plan is to leave that to "phase 2" of the project, if I manage to validate the basic web-ony prototype, as it is quite work intensive job, and my hope is that initially people will start by doing shorter edits of the size of a Stack Overflow answer, such that local editing might not be a must.

> Also, how would one find your contact information or -better yet- become your friend?

Pick the one you prefer from: https://cirosantilli.com/contact

You're already a friend :-)

Keep in touch if anything of interest comes up.
