### ISSUE TITLE
Are all page tables of all processes stored in RAM memory all the time?

### ISSUE THREAD

**Issue by nemuos** [cirosantilli/cirosantilli.github.io#9]
Are all page tables of all processes stored in RAM memory all the time?

**Comment by cirosantilli** [comment]
I am not sure, but I think it very likely that the kernel never swaps them to disk.

Otherwise, how would page faults be handled for the missing page tables?

The CPU would just do something random since the pages are not there.

**Comment by cirosantilli** [comment]
@nemuos I don't know :-)

Nut I don't see why it could not swap them out.

It would only have to ensure that those pages are present when the process is about to execute, which would cause a slight performance loss.

**Comment by nemuos** [comment]
@cirosantilli The base address of the page tables that are stored in page directory table, are those the linear addresses or physical addresses?

**Comment by cirosantilli** [comment]
@nemuos do you mean if they are linear or physical? I don't know, but I guess linear, otherwise it would feel weird, as you'd lose part of the segmentation protection.

Is this related to the first question? if not, let's move to another issue.

Also consider asking those things on Stack Overflow + what use case you have in mind, and ping me with the question or if you find the answer in some other way.
